name:                sat-solver
version:             0.1.0.0
github:              "githubuser/sat-solver-filip-plata"
license:             BSD3
author:              "Filip Plata"
maintainer:          "fp371335@students.mimuw.edu.pl"
copyright:           "2020 Filip Plata"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/logic-course/sat-solver-filip-plata>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:            lib
  dependencies:
    - parsec >= 3.1 && < 4
    - QuickCheck >= 2.13 && < 3
    - containers >= 0.6 && < 1

executables:
  sat-solver:
    main:                sat-solver.hs
    source-dirs:         app/solver
    dependencies:
      - sat-solver
